# Docker Compose para desarrollo local
version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    container_name: instagur-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: instagur
    volumes:
      - mongodb_data:/data/db
    networks:
      - instagur-network

  # Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: instagur-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/instagur?authSource=admin
      JWT_SECRET: dev_secret_change_in_production
      FRONTEND_URL: http://localhost:5173
    volumes:
      - ./backend/src:/app/src
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongodb
    networks:
      - instagur-network

  # Frontend (desarrollo)
  frontend:
    image: node:18-alpine
    container_name: instagur-frontend
    working_dir: /app
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - instagur-network

volumes:
  mongodb_data:

networks:
  instagur-network:
    driver: bridge
